version: '3'
services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/tailwind.conf:/etc/nginx/conf.d/tailwind.conf
      - my-data:/usr/share/nginx/html
    networks:
      - my-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container
    depends_on:
      - nginx
    networks:
      - my-network
volumes:
  my-data:
networks:
  my-network:
    driver: bridge

