export { default as Blog } from './Blog'
export { default as About } from './About'
export { default as Home } from './home/Home'
export { default as Contact } from './contact'
export { default as Portifolio } from './portfolio'
export { default as Services } from './Services/Services'
